version: "3.5"

services:
  build:
    image: contract-builder
    build:
      context: ../..
      dockerfile: ./scripts/docker/Dockerfile
    volumes:
      - ./build:/build:rw
      - ./deployments:/deployments:rw
    env_file:
      - .env
    command: "yarn deploy --network ${NETWORK}"